import { useSQLiteContext } from 'expo-sqlite';
import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, View } from 'react-native';

import { Button, Card, Field, MoneyField, Screen, Text } from '@/components';
import { createTransaction, deleteTransaction, findTransactionById, listAccounts, listCategories, updateTransaction } from '@/db/repositories';
import { formatBrazilianMoneyInput, parseCivilDate, parseMoneyInput, validateNotFuture, validateRequiredText } from '@/domain';
import type { Account, Category, Transaction } from '@/domain';
import { useTheme } from '@/theme/ThemeProvider';

export function ExpenseScreen({ kind = 'expense', onDone, transactionId }: { kind?: 'expense' | 'income'; onDone: () => void; transactionId?: number }) {
  const db = useSQLiteContext();
  const [accounts, setAccounts] = useState<readonly Account[]>([]); const [categories, setCategories] = useState<readonly Category[]>([]);
  const [accountId, setAccountId] = useState<number | null>(null); const [categoryId, setCategoryId] = useState<number | null>(null);
  const [name, setName] = useState(''); const [amount, setAmount] = useState(''); const [date, setDate] = useState(today()); const [description, setDescription] = useState(''); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const [existing, setExisting] = useState<Transaction | null>(null);
  useEffect(() => { void Promise.all([listAccounts(db), listCategories(db), transactionId ? findTransactionById(db, transactionId) : Promise.resolve(null)]).then(([a, c, item]) => { setAccounts(a); setCategories(c); if (item && (item.kind === 'expense' || item.kind === 'income')) { setExisting(item); setAccountId(item.accountId); setCategoryId(item.categoryId); setName(item.name); setAmount(formatBrazilianMoneyInput(Math.abs(item.amountCents))); setDate(item.transactionDate); setDescription(item.description ?? ''); } }); }, [db, transactionId]);
  async function save() {
    const money = parseMoneyInput(amount.replace(/\./g, '')); const civil = parseCivilDate(date); const validName = validateRequiredText(name);
    if (!validName.ok || !money.ok || !civil.ok || !validateNotFuture(civil.ok ? civil.value : '0001-01-01', today()).ok || accountId === null || (kind === 'expense' && categoryId === null)) { setError(`Preencha nome, valor, data, conta${kind === 'expense' ? ' e categoria' : ''}. A data não pode ser futura.`); return; }
    setSaving(true); try { const input = { kind, accountId, categoryId: kind === 'expense' ? categoryId : null, name: validName.value, description, amountCents: kind === 'expense' ? -money.value : money.value, transactionDate: civil.value } as const; if (existing) await updateTransaction(db, existing.id, input); else await createTransaction(db, input); onDone(); } catch { setError(`Não foi possível salvar ${kind === 'expense' ? 'a despesa' : 'a renda'}.`); } finally { setSaving(false); }
  }
  return <Screen><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text variant="heading">{existing ? 'Editar' : 'Nova'} {kind === 'expense' ? 'despesa' : 'renda'}</Text><Card elevated><View style={styles.form}><Field error={error ?? undefined} label="Nome" onChangeText={setName} value={name} placeholder={kind === 'expense' ? 'Ex.: Mercado' : 'Ex.: Salário'} /><MoneyField label="Valor" onChangeText={setAmount} value={amount} placeholder="0,00" /><Field label="Data" onChangeText={setDate} value={date} placeholder="AAAA-MM-DD" keyboardType="numbers-and-punctuation" /><Text tone="muted" variant="caption">Conta</Text><View style={styles.choices}>{accounts.map((a) => <Choice key={a.id} label={a.name} onPress={() => setAccountId(a.id)} selected={accountId === a.id} />)}</View>{kind === 'expense' ? <><Text tone="muted" variant="caption">Categoria</Text><View style={styles.choices}>{categories.map((c) => <Choice key={c.id} label={`${c.visualType === 'icon' ? c.visualValue : '●'} ${c.name}`} onPress={() => setCategoryId(c.id)} selected={categoryId === c.id} />)}</View></> : null}<Field label="Descrição (opcional)" onChangeText={setDescription} value={description} placeholder="Adicionar observação" multiline /><Button disabled={saving} label={saving ? 'Salvando…' : 'Salvar'} onPress={() => void save()} />{existing ? <Button label="Excluir lançamento" onPress={() => Alert.alert('Excluir lançamento?', 'Esta ação remove o lançamento e atualiza o saldo da conta.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: () => void deleteTransaction(db, existing.id).then(onDone) }])} variant="destructive" /> : null}<Button label="Cancelar" onPress={onDone} variant="ghost" /></View></Card></ScrollView></Screen>;
}
function Choice({ label, onPress, selected }: { label: string; onPress: () => void; selected: boolean }) { const { tokens } = useTheme(); return <Pressable onPress={onPress} style={[styles.choice, { backgroundColor: selected ? tokens.primary : tokens.surface, borderColor: selected ? tokens.primary : tokens.border }]}><Text variant="caption" style={{ color: selected ? tokens.onPrimary : tokens.text }}>{label}</Text></Pressable>; }
function today() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; }
const styles = StyleSheet.create({ choice: { borderRadius: 999, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 8 }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, content: { gap: 20, paddingVertical: 24 }, form: { gap: 16 } });
