import { useCallback, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';

import { Button, Card, Screen, Text } from '@/components';
import { listAccounts, listCategories, listTransactions } from '@/db/repositories';
import { calculateAccountBalance, formatBrazilianCurrency } from '@/domain';
import type { Account, Category, Transaction } from '@/domain';
import { useTheme } from '@/theme/ThemeProvider';

export function TransactionsHomeScreen({ onAppearance, onEditTransaction, onManageCategories, onNewExpense, onNewIncome, onNoAccounts }: { onAppearance: () => void; onEditTransaction: (id: number) => void; onManageCategories: () => void; onNewExpense: () => void; onNewIncome: () => void; onNoAccounts: () => void }) {
  const db = useSQLiteContext(); const { tokens } = useTheme(); const [accounts, setAccounts] = useState<readonly Account[]>([]); const [selectedAccountId, setSelectedAccountId] = useState<number | null>(null); const [allTransactions, setAllTransactions] = useState<readonly Transaction[]>([]); const [transactions, setTransactions] = useState<readonly Transaction[]>([]); const [categories, setCategories] = useState<readonly Category[]>([]); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { const [loadedAccounts, loadedTransactions, loadedCategories] = await Promise.all([listAccounts(db), listTransactions(db), listCategories(db)]); if (loadedAccounts.length === 0) { onNoAccounts(); return; } setAccounts(loadedAccounts); setSelectedAccountId((id) => id ?? loadedAccounts[0].id); setAllTransactions(loadedTransactions); setTransactions(loadedTransactions.filter((item) => item.kind === 'expense' || item.kind === 'income')); setCategories(loadedCategories); setError(null); } catch { setError('Não foi possível carregar os lançamentos.'); } }, [db, onNoAccounts]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const selectedAccount = accounts.find((item) => item.id === selectedAccountId) ?? null;
  return <Screen><ScrollView contentContainerStyle={styles.content}><View><Text variant="heading">Início</Text><Text tone="muted" style={{ marginTop: tokens.spacing.sm }}>Histórico de despesas e rendas.</Text></View>{selectedAccount ? <Card><Text tone="muted" variant="caption">Saldo atual</Text><Text variant="title">{selectedAccount.name}</Text><Text variant="heading">{formatBrazilianCurrency(calculateAccountBalance(allTransactions, selectedAccount.id))}</Text><View style={styles.accounts}>{accounts.map((account) => <Pressable key={account.id} onPress={() => setSelectedAccountId(account.id)} style={[styles.account, { borderColor: account.id === selectedAccountId ? tokens.primary : tokens.border }]}><Text variant="caption">{account.name}</Text></Pressable>)}</View></Card> : null}{error ? <Text tone="negative">{error}</Text> : null}<View style={styles.list}>{transactions.length === 0 ? <Card><Text tone="muted">Nenhum lançamento registrado ainda.</Text></Card> : transactions.map((transaction) => <Pressable key={transaction.id} onPress={() => onEditTransaction(transaction.id)}><TransactionCard category={categories.find((item) => item.id === transaction.categoryId) ?? null} transaction={transaction} /></Pressable>)}</View><Button label="Nova despesa" onPress={onNewExpense} /><Button label="Nova renda" onPress={onNewIncome} variant="secondary" /><Button label="Gerenciar categorias" onPress={onManageCategories} variant="ghost" /><Button label="Personalizar aparência" onPress={onAppearance} variant="ghost" /></ScrollView></Screen>;
}
function TransactionCard({ category, transaction }: { category: Category | null; transaction: Transaction }) { const income = transaction.kind === 'income'; return <Card><Text variant="title">{transaction.name}</Text><Text tone={income ? 'positive' : 'negative'}>{formatBrazilianCurrency(transaction.amountCents)}</Text><Text tone="muted" variant="caption">{transaction.transactionDate}{transaction.kind === 'expense' ? ` · ${category ? category.name : 'Categoria excluída'}` : ''}</Text></Card>; }
const styles = StyleSheet.create({ account: { borderRadius: 999, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 6 }, accounts: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 }, content: { gap: 18, paddingVertical: 24 }, list: { gap: 10 } });
